FROM nginx:latest
RUN echo '<h1>Hello World</h1>' > /usr/share/nginx/html/index.html

# BUILD IMAGE: docker image build -t CONTAINER-NAME .
# RUN CONTAINER: docker container run -p 80:80 CONTAINER-NAME