version: '3.8'

volumes: 
  dados:

networks:
  banco:
  web:
  fila:

services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Script
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuracao proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    depends_on:
      - app
    ports:
      - 80:80

  app:
    build: app
    volumes:
      # Aplicacao
      - ./app:/app
    working_dir: /app
    command: sender.py
    environment:
      - DB_NAME=email_sender
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue

  queue:
    image: redis:3.2
    networks:
      - fila

  worker:
    build: worker
    volumes:
      # Workers
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
